quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=weather
quarkus.datasource.password=weather
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/weatherdb?options=-c%20TimeZone%3DUTC

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.rest-client.open-meteo.url=https://api.open-meteo.com
quarkus.rest-client.geocoding-api.url=https://geocoding-api.open-meteo.com

quarkus.http.cors.enabled=false
